export const BaseUrl = "https://3ad5-2401-4900-8844-fee8-c9c3-7217-a15c-3c5c.ngrok-free.app";
// export const BaseUrl = "https://ddsp-backend.onrender.com";


export const loginApi = "api/user/userlogin";
export const logoutApi = "api/user/userlogout";
export const changePasswordApi = "api/user/UserUpdatePassword"
export const addFarmerInfoApi = "api/user/addfarmerinfo";
export const adminUserUpdateApi = "api/admin/userupdate";
export const getFarmerApi = "api/user/getFarmers";
export const addCultivationCostDetailsApi = "api/user/addCultivationCostDetails1";
export const addCultivationCostDetailsPostApi = "api/user/addCultivationCostDetails";
export const getProductionDetailsApi = "api/user/getProductionDetails";
export const addProductionDetailsApi = "api/user/addProductionDetails";
export const addWorkDetailsApi = "api/user/addworkdetails";
export const getFarmerByIdApi = "api/user/getfarmerbyid";
export const updateFarmerDetailsByIdApi = "api/user/updateFarmerDetails";
export const addFieldOfficerWorkDetailApi = "api/user/addFieldofficerWorkDetail";
export const detailofproductionandcultivationApi = "api/user/detailofproductionandcultivation"
export const workDetailApi = "api/user/workdetails";
export const getWorkDetailByIdApi = "api/user/workdetailsbyid";
export const updateWorkDetailsByIdApi = "api/user/updateworkdetailsbyid";
export const getLocationApi = "api/user/getalllocation";
export const getLocationByUserIdApi = "api/user/getlocationbyuserid";
export const addUserLocationApi = "api/user/adduserlocation";
export const deleteLocationByIdApi = "api/user/locationdeletebyid";
export const addInteractionApi= "api/user/addInteraction";
export const getFarmerListByUserIdApi = "api/user/farmerlistbyuserid";
export const getAllFieldOfficerApi = "api/user/allfieldofficer";
export const getAllAsstPCApi = "api/user/allasstpc";
export const getCoordinatorDetailsByIDApi = "api/user/getCoordinatorDetailsByID";
export const getFarmerInteractionApi = "api/user/getfarmerintration"
export const getInteractionDetailsApi = "api/user/interaction_details"
export const updateProductionDetailsApi = "api/user/updateproductiondetails";
export const updateCultivationDetailsApi = "api/user/updatecultivationdetail";